<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Qec.Itmg.UnitTests</RootNamespace>
    <AssemblyName>Qec.Itmg.UnitTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Qec.Itmg.BuildingBlocks\Qec.Itmg.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Qec.Itmg.Identity\Qec.Itmg.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organization\Qec.Itmg.Organization\Qec.Itmg.Organization.csproj" />
    <ProjectReference Include="..\..\src\Modules\Platform\Qec.Itmg.Platform\Qec.Itmg.Platform.csproj" />
    <ProjectReference Include="..\..\src\Qec.Itmg.Host\Qec.Itmg.Host.csproj" />
  </ItemGroup>
</Project>
