// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.Evidence.Persistence;

#nullable disable

namespace Qec.Itmg.Evidence.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    partial class EvidenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("evd")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceExpiryNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NotifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ValidToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId", "ValidToUtc", "ThresholdDays")
                        .IsUnique()
                        .HasDatabaseName("IX_EvidenceExpiryNotificationLog_Evidence_Date_Threshold");

                    b.ToTable("EvidenceExpiryNotificationLog", "evd");
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_EvidenceLink_Target");

                    b.HasIndex("EvidenceId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("IX_EvidenceLink_Evidence_Target");

                    b.ToTable("EvidenceLink", "evd");
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EvidenceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Classification")
                        .HasDatabaseName("IX_Evidence_Classification");

                    b.HasIndex("EvidenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Evidence_EvidenceNumber");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Evidence_OwnerUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Evidence_Status");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("IX_Evidence_ValidTo");

                    b.HasIndex("SourceType", "SourceRecordId")
                        .HasDatabaseName("IX_Evidence_Source");

                    b.ToTable("Evidence", "evd");
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_EvidenceVersion_Evidence_Version");

                    b.ToTable("EvidenceVersion", "evd");
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceExpiryNotificationLog", b =>
                {
                    b.HasOne("Qec.Itmg.Evidence.Domain.EvidenceRecord", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceLink", b =>
                {
                    b.HasOne("Qec.Itmg.Evidence.Domain.EvidenceRecord", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Evidence.Domain.EvidenceVersion", b =>
                {
                    b.HasOne("Qec.Itmg.Evidence.Domain.EvidenceRecord", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
