// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.DocumentManagement.Persistence;

#nullable disable

namespace Qec.Itmg.DocumentManagement.Persistence.Migrations
{
    [DbContext(typeof(DocumentManagementDbContext))]
    partial class DocumentManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("doc")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentGovernanceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DocumentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ManagedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedDocumentId", "LinkKind", "TargetKey")
                        .HasDatabaseName("IX_DocumentGovernanceLink_Doc_Kind_Target");

                    b.ToTable("DocumentGovernanceLink", "doc");
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentReviewNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NotifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReviewDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagedDocumentId", "ReviewDateUtc", "ThresholdDays")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentReviewNotificationLog_Doc_Date_Threshold");

                    b.ToTable("DocumentReviewNotificationLog", "doc");
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SupersedesVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagedDocumentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentVersion_Document_Version");

                    b.ToTable("DocumentVersion", "doc");
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.ManagedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignatedApproverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("EffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresAcknowledgement")
                        .HasColumnType("bit");

                    b.Property<string>("RetirementReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("ReviewDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Classification")
                        .HasDatabaseName("IX_ManagedDocument_Classification");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ManagedDocument_DocumentNumber");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_ManagedDocument_DocumentType");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_ManagedDocument_OwnerUserId");

                    b.HasIndex("ReviewDate")
                        .HasDatabaseName("IX_ManagedDocument_ReviewDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ManagedDocument_Status");

                    b.ToTable("ManagedDocument", "doc");
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.PolicyAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcknowledgedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PolicyAcknowledgement_Version_User");

                    b.HasIndex("ManagedDocumentId", "UserId")
                        .HasDatabaseName("IX_PolicyAcknowledgement_Document_User");

                    b.ToTable("PolicyAcknowledgement", "doc");
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentGovernanceLink", b =>
                {
                    b.HasOne("Qec.Itmg.DocumentManagement.Domain.ManagedDocument", null)
                        .WithMany()
                        .HasForeignKey("ManagedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentReviewNotificationLog", b =>
                {
                    b.HasOne("Qec.Itmg.DocumentManagement.Domain.ManagedDocument", null)
                        .WithMany()
                        .HasForeignKey("ManagedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.DocumentVersion", b =>
                {
                    b.HasOne("Qec.Itmg.DocumentManagement.Domain.ManagedDocument", null)
                        .WithMany()
                        .HasForeignKey("ManagedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.DocumentManagement.Domain.PolicyAcknowledgement", b =>
                {
                    b.HasOne("Qec.Itmg.DocumentManagement.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qec.Itmg.DocumentManagement.Domain.ManagedDocument", null)
                        .WithMany()
                        .HasForeignKey("ManagedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
