// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.AccessManagement.Persistence;

#nullable disable

namespace Qec.Itmg.AccessManagement.Persistence.Migrations
{
    [DbContext(typeof(AccessManagementDbContext))]
    [Migration("20260907101500_AddAccessCaseReworkAndRevisions")]
    partial class AddAccessCaseReworkAndRevisions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessCategoryKeySnapshot")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AccessCategoryNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentScopeRevisionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignatedApproverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EffectiveAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ExistingAccessConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ExistingAccessConfirmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExistingAccessConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FallbackReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("LinkedTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PreferSubjectEmployeeVerificationSnapshot")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("RejectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReturnedForReworkAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReturnedForReworkByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReworkReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SubjectEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerificationComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VerificationOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessCategoryId")
                        .HasDatabaseName("IX_AccessCase_AccessCategoryId");

                    b.HasIndex("CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCase_CaseNumber");

                    b.HasIndex("EffectiveAtUtc")
                        .HasDatabaseName("IX_AccessCase_EffectiveAtUtc");

                    b.HasIndex("RequesterUserId")
                        .HasDatabaseName("IX_AccessCase_RequesterUserId");

                    b.HasIndex("SubjectUserId")
                        .HasDatabaseName("IX_AccessCase_SubjectUserId");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_AccessCase_VendorId");

                    b.HasIndex("Status", "Type")
                        .HasDatabaseName("IX_AccessCase_Status_Type");

                    b.ToTable("AccessCase", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("RelatedSodRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccessCaseId", "Type")
                        .HasDatabaseName("IX_AccessCaseException_Case_Type");

                    b.ToTable("AccessCaseException", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessEntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntitlementKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntitlementNameArSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntitlementNameEnSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("FulfilledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FulfilledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccessEntitlementId")
                        .HasDatabaseName("IX_AccessCaseItem_AccessEntitlementId");

                    b.HasIndex("EntitlementKey")
                        .HasDatabaseName("IX_AccessCaseItem_EntitlementKey");

                    b.HasIndex("AccessCaseId", "Status")
                        .HasDatabaseName("IX_AccessCaseItem_Case_Status");

                    b.ToTable("AccessCaseItem", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRouteParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsSubjectEmployeeDerived")
                        .HasColumnType("bit");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Stage")
                        .HasDatabaseName("IX_AccessCaseRouteParticipant_User_Stage");

                    b.HasIndex("AccessCaseId", "Stage", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCaseRouteParticipant_Case_Stage_User");

                    b.ToTable("AccessCaseRouteParticipant", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessCaseId", "Decision")
                        .HasDatabaseName("IX_AccessCaseRevision_Case_Decision");

                    b.HasIndex("AccessCaseId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCaseRevision_Case_RevisionNumber");

                    b.ToTable("AccessCaseRevision", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRevisionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessEntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CustomName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntitlementKeySnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("bit");

                    b.Property<string>("NameArSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameEnSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessEntitlementId");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("IX_AccessCaseRevisionItem_RevisionId");

                    b.ToTable("AccessCaseRevisionItem", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PreferSubjectEmployeeVerification")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AccessCategory_IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCategory_Key");

                    b.ToTable("AccessCategory", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCategoryEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessEntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultForJoiner")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccessEntitlementId");

                    b.HasIndex("AccessCategoryId", "AccessEntitlementId")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCategoryEntitlement_Category_Entitlement");

                    b.HasIndex("AccessCategoryId", "SortOrder")
                        .HasDatabaseName("IX_AccessCategoryEntitlement_Category_Sort");

                    b.ToTable("AccessCategoryEntitlement", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCategoryParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessCategoryId", "Stage", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessCategoryParticipant_Category_Stage_User");

                    b.ToTable("AccessCategoryParticipant", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultRevokeAction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AccessEntitlement_IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessEntitlement_Key");

                    b.ToTable("AccessEntitlement", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessReviewCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerUserId")
                        .HasDatabaseName("IX_AccessReviewCampaign_Reviewer");

                    b.HasIndex("Status", "DueAtUtc")
                        .HasDatabaseName("IX_AccessReviewCampaign_Status_Due");

                    b.ToTable("AccessReviewCampaign", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("AccountRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Decision")
                        .HasDatabaseName("IX_AccessReviewItem_Campaign_Decision");

                    b.ToTable("AccessReviewItem", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.ExistingAccessSnapshotItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntitlementKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccessCaseId")
                        .HasDatabaseName("IX_ExistingAccessSnapshotItem_Case");

                    b.ToTable("ExistingAccessSnapshotItem", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.ManagedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .HasDatabaseName("IX_ManagedAccount_AccountName");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_ManagedAccount_OwnerUserId");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_ManagedAccount_VendorId");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("IX_ManagedAccount_Type_Status");

                    b.ToTable("ManagedAccount", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.SodRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeftEntitlementKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RightEntitlementKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SodRule_IsActive");

                    b.HasIndex("LeftEntitlementKey", "RightEntitlementKey")
                        .HasDatabaseName("IX_SodRule_Left_Right");

                    b.ToTable("SodRule", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.UserAccessEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessEntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntitlementKeySnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntitlementNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GrantedFromAccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastChangedFromAccessCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessEntitlementId");

                    b.HasIndex("UserId", "AccessEntitlementId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAccessEntitlement_User_Entitlement_Active")
                        .HasFilter("[AccessEntitlementId] IS NOT NULL AND [Status] = N'Active'");

                    b.HasIndex("UserId", "EntitlementKeySnapshot")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAccessEntitlement_User_Key_Active")
                        .HasFilter("[AccessEntitlementId] IS NULL AND [Status] = N'Active'");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_UserAccessEntitlement_User_Status");

                    b.ToTable("UserAccessEntitlement", "acc");
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseException", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCase", null)
                        .WithMany()
                        .HasForeignKey("AccessCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseItem", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCase", null)
                        .WithMany()
                        .HasForeignKey("AccessCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessEntitlement", null)
                        .WithMany()
                        .HasForeignKey("AccessEntitlementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRouteParticipant", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCase", null)
                        .WithMany()
                        .HasForeignKey("AccessCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRevision", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCase", null)
                        .WithMany()
                        .HasForeignKey("AccessCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCaseRevisionItem", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessEntitlement", null)
                        .WithMany()
                        .HasForeignKey("AccessEntitlementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCaseRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCategoryEntitlement", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCategory", null)
                        .WithMany()
                        .HasForeignKey("AccessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessEntitlement", null)
                        .WithMany()
                        .HasForeignKey("AccessEntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessCategoryParticipant", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCategory", null)
                        .WithMany()
                        .HasForeignKey("AccessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.AccessReviewItem", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessReviewCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.ExistingAccessSnapshotItem", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessCase", null)
                        .WithMany()
                        .HasForeignKey("AccessCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.AccessManagement.Domain.UserAccessEntitlement", b =>
                {
                    b.HasOne("Qec.Itmg.AccessManagement.Domain.AccessEntitlement", null)
                        .WithMany()
                        .HasForeignKey("AccessEntitlementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
