// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.Security.Persistence;

#nullable disable

namespace Qec.Itmg.Security.Persistence.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    [Migration("20260907123930_AddAwarenessCampaignStarterKey")]
    partial class AddAwarenessCampaignStarterKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sec")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .HasDatabaseName("IX_AwarenessAnswer_Question_Order");

                    b.ToTable("AwarenessAnswerOption", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("CampaignVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("IX_AwarenessAttempt_AssignmentId");

                    b.HasIndex("CampaignVersionId")
                        .HasDatabaseName("IX_AwarenessAttempt_CampaignVersionId");

                    b.HasIndex("AssignmentId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessAttempt_Assignment_Number");

                    b.ToTable("AwarenessAttempt", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAudienceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_AwarenessAudienceRule_CampaignId");

                    b.ToTable("AwarenessAudienceRule", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowRetry")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModuleVersion")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PassThresholdPercent")
                        .HasColumnType("int");

                    b.Property<Guid?>("PublishedVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireCompletion")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireQuiz")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StarterKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("IX_AwarenessCampaign_DueAtUtc");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_AwarenessCampaign_ModuleId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessCampaign_Number")
                        .HasFilter("[Number] IS NOT NULL");

                    b.HasIndex("PublishedVersionId")
                        .HasDatabaseName("IX_AwarenessCampaign_PublishedVersionId");

                    b.HasIndex("StarterKey")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessCampaign_StarterKey")
                        .HasFilter("[StarterKey] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AwarenessCampaign_Status");

                    b.ToTable("AwarenessCampaign", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaignQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExplanationAr")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExplanationEn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SortOrder")
                        .HasDatabaseName("IX_AwarenessCampaignQuestion_Campaign_Order");

                    b.HasIndex("CampaignVersionId", "SortOrder")
                        .HasDatabaseName("IX_AwarenessCampaignQuestion_Version_Order");

                    b.ToTable("AwarenessCampaignQuestion", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaignQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "SortOrder")
                        .HasDatabaseName("IX_AwarenessCampaignQuestionOption_Order");

                    b.ToTable("AwarenessCampaignQuestionOption", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaignVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowRetry")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("PassingScorePercent")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireQuiz")
                        .HasColumnType("bit");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessCampaignVersion_Campaign_Number");

                    b.ToTable("AwarenessCampaignVersion", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssignmentSource")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModuleVersion")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("PassedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotDepartmentName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotPositionNames")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SnapshotUpn")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid?>("SourceDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourcePositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("IX_AwarenessCompletion_DueAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AwarenessCompletion_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AwarenessCompletion_UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessCompletion_Campaign_User");

                    b.HasIndex("CampaignVersionId", "UserId")
                        .HasDatabaseName("IX_AwarenessCompletion_Version_User");

                    b.ToTable("AwarenessCompletion", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyAr")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyEn")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SortOrder")
                        .HasDatabaseName("IX_AwarenessContentBlock_Campaign_Order");

                    b.HasIndex("CampaignVersionId", "SortOrder")
                        .HasDatabaseName("IX_AwarenessContentBlock_Version_Order");

                    b.ToTable("AwarenessContentBlock", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PassThresholdPercent")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessModule_Code");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AwarenessModule_Status");

                    b.ToTable("AwarenessModule", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "DisplayOrder")
                        .HasDatabaseName("IX_AwarenessQuestion_Module_Order");

                    b.ToTable("AwarenessQuestion", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessQuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedOptionIdsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessQuizAnswer_Attempt_Question");

                    b.ToTable("AwarenessQuizAnswer", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessReminderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NotifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReminderKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "ReminderKind")
                        .IsUnique()
                        .HasDatabaseName("IX_AwarenessReminder_Assignment_Kind");

                    b.ToTable("AwarenessReminderLog", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.ExceptionExpiryNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionId", "EventKey")
                        .IsUnique()
                        .HasDatabaseName("IX_ExceptionExpiryNotificationLog_Unique");

                    b.ToTable("ExceptionExpiryNotificationLog", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.PenetrationTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PentestNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Provider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ReportEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PentestNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PenetrationTest_Number");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_PenetrationTest_StartDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PenetrationTest_Status");

                    b.ToTable("PenetrationTest", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.PentestFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuditFindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PenetrationTestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("VulnerabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PenetrationTestId", "Status")
                        .HasDatabaseName("IX_PentestFinding_Test_Status");

                    b.ToTable("PentestFinding", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.PolicyException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompensatingControls")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExceptionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("InternalControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RiskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PolicyException_Number");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_PolicyException_ExpiresAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PolicyException_Status");

                    b.ToTable("PolicyException", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<int>("InherentScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("InternalControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ResidualImpact")
                        .HasColumnType("int");

                    b.Property<int?>("ResidualLikelihood")
                        .HasColumnType("int");

                    b.Property<int?>("ResidualScore")
                        .HasColumnType("int");

                    b.Property<string>("RiskNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TreatmentPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InherentScore")
                        .HasDatabaseName("IX_Risk_InherentScore");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Risk_Owner");

                    b.HasIndex("ResidualScore")
                        .HasDatabaseName("IX_Risk_ResidualScore");

                    b.HasIndex("RiskNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Risk_Number");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Risk_Status");

                    b.ToTable("Risk", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.RiskLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RiskId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("IX_RiskLink_Unique");

                    b.ToTable("RiskLink", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.Vulnerability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptedRiskReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VulnerabilityNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationItemId")
                        .HasDatabaseName("IX_Vulnerability_CI");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("IX_Vulnerability_DueAtUtc");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_Vulnerability_Severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Vulnerability_Status");

                    b.HasIndex("VulnerabilityNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Vulnerability_Number");

                    b.ToTable("Vulnerability", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.VulnerabilityRemediationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VulnerabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VulnerabilityId", "LinkType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("IX_VulnerabilityRemediationLink_Unique");

                    b.ToTable("VulnerabilityRemediationLink", "sec");
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAnswerOption", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAttempt", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCompletion", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessAudienceRule", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaignQuestionOption", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCampaignQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCampaignVersion", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessCompletion", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessQuestion", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessQuizAnswer", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessAttempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.AwarenessReminderLog", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.AwarenessCompletion", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.ExceptionExpiryNotificationLog", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.PolicyException", null)
                        .WithMany()
                        .HasForeignKey("ExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.PentestFinding", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.PenetrationTest", null)
                        .WithMany()
                        .HasForeignKey("PenetrationTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.RiskLink", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.Risk", null)
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Security.Domain.VulnerabilityRemediationLink", b =>
                {
                    b.HasOne("Qec.Itmg.Security.Domain.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
