// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.Reporting.Persistence;

#nullable disable

namespace Qec.Itmg.Reporting.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260905083957_P18_AdvancedReporting")]
    partial class P18_AdvancedReporting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rpt")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.Reporting.Domain.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PeriodEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PeriodStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SnapshotDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStartUtc")
                        .HasDatabaseName("IX_ReportSnapshot_PeriodStart");

                    b.HasIndex("SnapshotDateUtc")
                        .HasDatabaseName("IX_ReportSnapshot_Date");

                    b.HasIndex("SnapshotKey", "SnapshotDateUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_ReportSnapshot_Key_Date");

                    b.ToTable("ReportSnapshot", "rpt");
                });
#pragma warning restore 612, 618
        }
    }
}
