// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.Compliance.Persistence;

#nullable disable

namespace Qec.Itmg.Compliance.Persistence.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20260904130912_P12_ComplianceFrameworkMapping")]
    partial class P12_ComplianceFrameworkMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cmp")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.ComplianceCalendarItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FrameworkVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InternalControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("IX_ComplianceCalendarItem_DueAt");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_ComplianceCalendarItem_Owner");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ComplianceCalendarItem_Status");

                    b.ToTable("ComplianceCalendarItem", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.ControlAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssessmentDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssessorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FrameworkVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InternalControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TestProcedureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentDateUtc")
                        .HasDatabaseName("IX_ControlAssessment_AssessmentDate");

                    b.HasIndex("FrameworkVersionId")
                        .HasDatabaseName("IX_ControlAssessment_FrameworkVersion");

                    b.HasIndex("InternalControlId", "Status")
                        .HasDatabaseName("IX_ControlAssessment_Control_Status");

                    b.ToTable("ControlAssessment", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.ControlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FrameworkRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InternalControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkRequirementId");

                    b.HasIndex("InternalControlId", "FrameworkRequirementId")
                        .IsUnique()
                        .HasDatabaseName("IX_ControlMapping_Control_Requirement");

                    b.ToTable("ControlMapping", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.Framework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Framework_Code");

                    b.ToTable("Framework", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.FrameworkRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRequirementId")
                        .HasDatabaseName("IX_FrameworkRequirement_Parent");

                    b.HasIndex("FrameworkVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_FrameworkRequirement_Version_Code");

                    b.ToTable("FrameworkRequirement", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.FrameworkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId", "VersionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_FrameworkVersion_Framework_Version");

                    b.ToTable("FrameworkVersion", "cmp");
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.ControlMapping", b =>
                {
                    b.HasOne("Qec.Itmg.Compliance.Domain.FrameworkRequirement", null)
                        .WithMany()
                        .HasForeignKey("FrameworkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.FrameworkRequirement", b =>
                {
                    b.HasOne("Qec.Itmg.Compliance.Domain.FrameworkVersion", null)
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qec.Itmg.Compliance.Domain.FrameworkRequirement", null)
                        .WithMany()
                        .HasForeignKey("ParentRequirementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Qec.Itmg.Compliance.Domain.FrameworkVersion", b =>
                {
                    b.HasOne("Qec.Itmg.Compliance.Domain.Framework", null)
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
