// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.RemoteSupport.Persistence;

#nullable disable

namespace Qec.Itmg.RemoteSupport.Persistence.Migrations
{
    [DbContext(typeof(RemoteSupportDbContext))]
    [Migration("20260905182935_OnDemandRemoteEndpoints")]
    partial class OnDemandRemoteEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rem")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Architecture")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentRemoteSessionRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EndpointKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EngineNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HelperVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionStatus")
                        .HasDatabaseName("IX_RemoteEndpoint_ConnectionStatus");

                    b.HasIndex("CurrentRemoteSessionRequestId")
                        .HasDatabaseName("IX_RemoteEndpoint_CurrentSession");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_RemoteEndpoint_ExpiresAtUtc");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_RemoteEndpoint_OwnerUserId");

                    b.ToTable("RemoteEndpoint", "rem");
                });

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteEndpointEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RemoteSessionRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RemoteSessionRequestId")
                        .HasDatabaseName("IX_RemoteEndpointEnrollment_Session");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RemoteEndpointEnrollment_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RemoteEndpointEnrollment_UserId");

                    b.ToTable("RemoteEndpointEnrollment", "rem");
                });

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteSessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RemoteSessionRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SystemEventKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RemoteSessionRequestId", "SentAtUtc")
                        .HasDatabaseName("IX_RemoteSessionMessage_Session_Sent");

                    b.ToTable("RemoteSessionMessage", "rem");
                });

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteSessionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AllowedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConnectingAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConsentIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ConsentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeclinedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("ElevationUsed")
                        .HasColumnType("bit");

                    b.Property<string>("EndReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineJoinUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("EngineSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastEngineError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("MfaSatisfiedAtStart")
                        .HasColumnType("bit");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecordingReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("RemoteEndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RemoteNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedPrivileges")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TechnicianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId")
                        .HasDatabaseName("IX_RemoteSessionRequest_ChangeRequestId");

                    b.HasIndex("ConfigurationItemId")
                        .HasDatabaseName("IX_RemoteSessionRequest_ConfigurationItemId");

                    b.HasIndex("EngineSessionId")
                        .HasDatabaseName("IX_RemoteSessionRequest_EngineSessionId");

                    b.HasIndex("RemoteEndpointId")
                        .HasDatabaseName("IX_RemoteSessionRequest_RemoteEndpointId");

                    b.HasIndex("RemoteNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_RemoteSessionRequest_RemoteNumber");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("IX_RemoteSessionRequest_RequestedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RemoteSessionRequest_Status");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TargetUserId");

                    b.HasIndex("TechnicianUserId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TechnicianUserId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TicketId");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("IX_RemoteSessionRequest_ActiveLookup");

                    b.ToTable("RemoteSessionRequest", "rem");
                });

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteEndpointEnrollment", b =>
                {
                    b.HasOne("Qec.Itmg.RemoteSupport.Domain.RemoteSessionRequest", null)
                        .WithMany()
                        .HasForeignKey("RemoteSessionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteSessionMessage", b =>
                {
                    b.HasOne("Qec.Itmg.RemoteSupport.Domain.RemoteSessionRequest", null)
                        .WithMany()
                        .HasForeignKey("RemoteSessionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
