// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qec.Itmg.RemoteSupport.Persistence;

#nullable disable

namespace Qec.Itmg.RemoteSupport.Persistence.Migrations
{
    [DbContext(typeof(RemoteSupportDbContext))]
    [Migration("20260905104726_P7_RemoteSupport")]
    partial class P7_RemoteSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rem")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qec.Itmg.RemoteSupport.Domain.RemoteSessionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AllowedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConnectingAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConsentIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ConsentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeclinedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("ElevationUsed")
                        .HasColumnType("bit");

                    b.Property<string>("EndReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineJoinUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("EngineSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastEngineError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("MfaSatisfiedAtStart")
                        .HasColumnType("bit");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecordingReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RemoteNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedPrivileges")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TechnicianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId")
                        .HasDatabaseName("IX_RemoteSessionRequest_ChangeRequestId");

                    b.HasIndex("ConfigurationItemId")
                        .HasDatabaseName("IX_RemoteSessionRequest_ConfigurationItemId");

                    b.HasIndex("EngineSessionId")
                        .HasDatabaseName("IX_RemoteSessionRequest_EngineSessionId");

                    b.HasIndex("RemoteNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_RemoteSessionRequest_RemoteNumber");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("IX_RemoteSessionRequest_RequestedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RemoteSessionRequest_Status");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TargetUserId");

                    b.HasIndex("TechnicianUserId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TechnicianUserId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_RemoteSessionRequest_TicketId");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("IX_RemoteSessionRequest_ActiveLookup");

                    b.ToTable("RemoteSessionRequest", "rem");
                });
#pragma warning restore 612, 618
        }
    }
}
